apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: eu.gcr.io/google_containers/hyperkube:v1.3.3
    command:
    - /hyperkube
    - proxy
    - --master=http://127.0.0.1:8080
    - --proxy-mode=iptables
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/
      name: etcssl
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/ssl
    name: etcssl
